# 

In [19]:
import numpy as np

In [21]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [22]:
a=[1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [24]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [25]:
l=[[1,2,3,4,],[5,6,7,8],[9,10,11,12,]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [26]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [35]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [43]:
arr=np.random.rand(10)
arr

array([0.063466  , 0.08035795, 0.29197354, 0.4247028 , 0.18963115,
       0.56171483, 0.96931551, 0.46546303, 0.89855181, 0.41891648])

In [45]:
arr=np.random.randn(10)
arr

array([-0.69196071,  0.67084982, -0.62222256,  0.07392949, -0.97366619,
       -0.00510628, -1.54792844,  2.31400957, -1.82789146, -1.11742899])

In [48]:
arr=np.random.randint(10,20,10)
arr

array([14, 11, 14, 11, 19, 18, 19, 15, 12, 16])

In [50]:
arr=np.array([[1,2,3],[4,5,6,],[7,8,9,]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.shape

(3, 3)

In [52]:
arr.size

9

In [53]:
arr.dtype

dtype('int64')

In [ ]:
Array Methods

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr.min()

np.int64(1)

In [56]:
arr.max()

np.int64(9)

In [57]:
arr.sum()

np.int64(45)

In [58]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [59]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [61]:
arr.mean()

np.float64(5.0)

In [62]:
arr.argmax()

np.int64(8)

In [63]:
arr.argmin()

np.int64(0)

In [64]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [66]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [67]:
 import numpy as np

In [ ]:
NumPy Indexing and Slicing of Vectors

In [69]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
arr[9]

np.int64(20)

In [74]:
arr[1:5]

array([12, 13, 14, 15])

In [75]:
arr[:5]

array([11, 12, 13, 14, 15])

In [76]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [78]:
arr_slic=arr[3::2]
arr_slic

array([14, 16, 18, 20])

In [80]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [81]:
arr[0]

array([1, 2, 3, 4, 5])

In [82]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[5]

array([26, 27, 28, 29, 30])

In [85]:
arr[0,4]

np.int64(5)

In [87]:
arr[5,4]

np.int64(30)

In [89]:
slici=arr[0:2,1:3]
slici

array([[2, 3],
       [7, 8]])

In [91]:
sl=arr[3:,3:]
sl

array([[19, 20],
       [24, 25],
       [29, 30]])

In [92]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [107]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [108]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [109]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
ARRAY OPERATION

In [110]:
import numpy as np

In [121]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [124]:
arr2=a1+a2
arr2

array([ 7,  9, 11, 13, 15])

In [125]:
a1-a2

array([-5, -5, -5, -5, -5])

In [126]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [127]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [128]:
a1//a2

array([0, 0, 0, 0, 0])

In [129]:
a2**a1

array([     6,     49,    512,   6561, 100000])

In [131]:
l=(10,20,30,40)
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [132]:
arr+10

array([20, 30, 40, 50])

In [137]:
arr1=np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [138]:
arr1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [140]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [ ]:
Deep and Shallow Copy

In [156]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [157]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [158]:
a[4:6]*10

array([50, 60])

In [164]:
a
b=a

In [165]:
b[0]=90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [166]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [168]:
#MATRIX OPERATION

In [169]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [170]:
A

array([[1, 2],
       [3, 4]])

In [171]:
B

array([[5, 6],
       [7, 8]])

In [172]:
A*B

array([[ 5, 12],
       [21, 32]])

In [173]:
A@B

array([[19, 22],
       [43, 50]])

In [174]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [175]:
A

array([[1, 2],
       [3, 4]])

In [176]:
A.T

array([[1, 3],
       [2, 4]])

In [185]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [186]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [187]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [189]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [190]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [195]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [198]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
 # Exercises for numpy 

In [228]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [229]:
# import numpy as np
b=np.sum(s,axis=1)
for i in b:
    if i!= 45:
        print ("sudoku is not valid ")
        break
    else:
        print("sudoku is valid for row")

sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row
sudoku is valid for row


In [230]:
c=np.sum(s,axis=0)
for i in c:
    if i!= 45:
        print ("sudoku is not valid ")
        break
    else:
        print("sudoku is valid for column")

sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column
sudoku is valid for column


In [233]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [272]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [273]:
data.shape

(5, 3)

In [274]:
np.mean(data[:,0])

np.float64(18.4)

In [275]:
data[:,1]

array([85, 92, 76, 65, 90])

In [276]:
np.max(data[:,2])

np.int64(95)

In [277]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [278]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [279]:
len(data[data[:,0]<19])

3

In [280]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [281]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [282]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [283]:
data[:,2] [data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])